Repository milvus-io/pymilvus-orm, pull requests merged in 2021-08, with the labels that each got.

#271 update pymilvus version
  requirements.txt
  setup.py
Labels: approved, ci-passed, size/XS

#272 Fixbug: return bool instead of tuple
  pymilvus_orm/utility.py
  tests/mock_milvus.py
Labels: approved, ci-passed, lgtm, size/S

#269 Expose timeout parameter
  pymilvus_orm/collection.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
Labels: approved, ci-passed, lgtm, size/L

#273 Update pymilvus version, change logic of waiting for load
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#275 Add rc3 for README
  README.md
Labels: size/XS, lgtm, approved, ci-passed

#276 Add query example doc
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
Labels: size/M, lgtm, approved, ci-passed, PR | cherry-pick

#278 Update pymilvus version
  setup.py
Labels: size/XS, lgtm, approved, ci-passed

#279 Change recommended version to 2.0.0rc4
  README.md
Labels: size/XS, lgtm, approved, ci-passed

#287 Archive pymilvus-orm
  README.md
Labels: size/XS, lgtm, approved, ci-passed
