Repository milvus-io/pymilvus-orm, pull requests merged in 2021-07, with the labels that each got.

#221 Add repr function for collection
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
Labels: approved, ci-passed, lgtm, size/S

#222 Fix bug for misspell
  pymilvus_orm/collection.py
Labels: approved, ci-passed, lgtm, size/XS

#230 Update pymilvus version
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#231 Support human readable mutation result
  pymilvus_orm/search.py
  tests/mock_milvus.py
  tests/mock_result.py
  tests/test_collection.py
Labels: approved, ci-passed, lgtm, size/M

#233 Update docs
  .gitignore
  docs/source/about.rst
  docs/source/changes.rst
  docs/source/contribute.rst
  docs/source/faq.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/param.rst
  docs/source/res/chang_log.md
  docs/source/results.rst
  docs/source/tutorial.rst
Labels: approved, ci-passed, lgtm, size/M

#225 Add slack channel into readme
  README.md
Labels: PR | cherry-pick, approved, ci-passed, lgtm, size/XS

#235 update action for docs(latest name is web-content)
  .github/workflows/release_event.yml
  .github/workflows/update_branch_doc_event.yml
Labels: PR | cherry-pick, approved, ci-passed, lgtm, size/S

#240 Fix tutorial docs
  docs/source/tutorial.rst
Labels: approved, ci-passed, lgtm, size/XS

#237 MutationResult should be placed in insert.py instead of search.py
  pymilvus_orm/collection.py
  pymilvus_orm/future.py
  pymilvus_orm/mutation.py
  pymilvus_orm/partition.py
  pymilvus_orm/search.py
Labels: approved, ci-passed, lgtm, size/L

#241 update code sample
  docs/source/tutorial.rst
Labels: PR | cherry-pick, approved, ci-passed, lgtm, size/S

#242 Remove soft link mock_milvus.py in examples/
  docs/source/install.rst
  examples/mock_milvus.py
Labels: PR | cherry-pick, approved, ci-passed, lgtm, size/XS

#244 Add query doc
  docs/source/api/collection.rst
  docs/source/api/partition.rst
Labels: approved, ci-passed, lgtm, size/M

#243 Add note for inserting sample
  docs/source/tutorial.rst
Labels: approved, ci-passed, lgtm, size/XS

#245 Fix doc link bug
  docs/source/tutorial.rst
Labels: approved, ci-passed, lgtm, size/XS

#247 Upgrade pymilvus
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#248 Construct partition without check
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
Labels: approved, ci-passed, lgtm, size/XS

#251 update orm version
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#252 Update pymilvus version
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#253 Prepare for the release of version 2.0.0rc2
  README.md
  docs/source/install.rst
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/S

#250 implement calc_distance()
  pymilvus_orm/utility.py
Labels: approved, ci-passed, lgtm, size/M

#255 Fixbug: Add dependency link to pypi.org
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#256 Update Doc:install a specific version package from test.pypi
  README.md
Labels: approved, ci-passed, lgtm, size/XS

#257 refine result of calc_distance()
  examples/example.py
  pymilvus_orm/constants.py
  pymilvus_orm/exceptions.py
  pymilvus_orm/utility.py
Labels: approved, ci-passed, lgtm, size/M

#254 Fix small typo in documentation
  examples/example.py
  examples/example_index.py
  pymilvus_orm/schema.py
  pymilvus_orm/utility.py
Labels: approved, ci-passed, lgtm, size/S

#259 update pymilvus version
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#263 Update pymilvus version
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#262 Unify the name of using
  pymilvus_orm/collection.py
Labels: approved, ci-passed, lgtm, size/S

#265 Change DataFrame validation location selection to integer-location
  pymilvus_orm/collection.py
Labels: approved, ci-passed, lgtm, size/XS

#268 Update pymilvus version
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#270 Update version of pymilvus
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/XS
