Repository milvus-io/pymilvus-orm, pull requests merged in 2021-05, with the labels that each got.

#112 Add logic of parse fields from pandas dataframe
  pymilvus_orm/collection.py
  pymilvus_orm/exceptions.py
  pymilvus_orm/schema.py
  pymilvus_orm/types.py
  tests/test_schema.py
  tests/test_types.py
Labels: pr/automerge

#115 Improve example and unittest
  pymilvus_orm/collection.py
  tests/utils.py
Labels: pr/automerge

#116 Fix bug for insert data about pandas.DataFrame
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
  pymilvus_orm/prepare.py
Labels: pr/automerge

#117 Add search implementation in Partition
  pymilvus_orm/partition.py
Labels: pr/automerge

#118 Add documentation of SearchResultFuture
  docs/source/api/schema.rst
  docs/source/api/search.rst
  pymilvus_orm/__init__.py
Labels: pr/automerge

#120 Add documentation of InsertFuture
  docs/source/api/api.rst
  docs/source/api/future.rst
  docs/source/api/search.rst
  pymilvus_orm/__init__.py
  pymilvus_orm/collection.py
  pymilvus_orm/future.py
  pymilvus_orm/partition.py
  pymilvus_orm/search.py
Labels: pr/automerge

#121 Fix bug with raising exception
  pymilvus_orm/collection.py
Labels: pr/automerge

#119 Improve connections interface
  pymilvus_orm/__init__.py
  pymilvus_orm/connections.py
  tests/mock_milvus.py
  tests/test_connections.py
Labels: pr/automerge

#124 Implement the num_entities of partition by get_partition_stats
  pymilvus_orm/partition.py
  requirements.txt
  tests/mock_milvus.py
  tests/test_partition.py
Labels: pr/automerge, size/M

#125 Add pylint check to github action
  .github/workflows/lint.yml
  Makefile
  pymilvus_orm/__init__.py
  pymilvus_orm/collection.py
  pymilvus_orm/connections.py
  pymilvus_orm/constants.py
  pymilvus_orm/default_config.py
  pymilvus_orm/exceptions.py
  pymilvus_orm/future.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
  pymilvus_orm/prepare.py
  pymilvus_orm/schema.py
  pymilvus_orm/search.py
  pymilvus_orm/types.py
  pymilvus_orm/utility.py
  requirements.txt
Labels: pr/automerge, size/XL

#126 Fix bug for connection get_connection
  pymilvus_orm/connections.py
Labels: pr/automerge, size/XS

#127 Change some function logic of Connections
  pymilvus_orm/connections.py
  tests/test_connections.py
Labels: pr/automerge, size/M

#128 Fix bug for checking data
  pymilvus_orm/schema.py
  pymilvus_orm/types.py
Labels: pr/automerge, size/XS

#129 Fix bug for creating a collection with two primary field
  pymilvus_orm/prepare.py
  pymilvus_orm/schema.py
Labels: pr/automerge, size/S

#130 Create connection when configure connection
  pymilvus_orm/connections.py
Labels: pr/automerge, size/XS

#131 Change dependency to pymilvus
  requirements.txt
Labels: approved, lgtm, pr/automerge, size/XS

#133 Fix bug: add dependency_links to setup.py
  setup.py
Labels: approved, lgtm, pr/automerge, size/S

#134 Fix bug: infer binary_vector failed
  examples/collection.py
  examples/hello_milvus.py
  pymilvus_orm/types.py
  setup.py
  tests/test_types.py
Labels: approved, lgtm, pr/automerge, size/S

#135 Add package workflow and organize dependent packages
  .github/workflows/package.yml
  .gitignore
  pymilvus_orm/__init__.py
  requirements.txt
  setup.py
Labels: approved, lgtm, size/L

#136 Implement connections class by single instance
  pymilvus_orm/connections.py
Labels: approved, pr/automerge, size/S

#137 Fix bug: rename master to main
  .github/workflows/package.yml
Labels: approved, lgtm, pr/automerge, size/XS

#139 Fix bug: actions should use master branch
  .github/workflows/package.yml
Labels: approved, lgtm, pr/automerge, size/XS

#138 The type of the data inserted into the collection must be like list
  pymilvus_orm/exceptions.py
  pymilvus_orm/schema.py
Labels: approved, lgtm, pr/automerge, size/S

#140 Check schema when creating collection
  pymilvus_orm/collection.py
  pymilvus_orm/schema.py
Labels: lgtm, size/S
