Repository milvus-io/pymilvus-orm, pull requests merged in 2021-04, with the labels that each got.

#40 Implement Collection.insert, Support list and tuple
  docs/draft/collection.md
  pymilvus_orm/collection.py
  pymilvus_orm/constants.py
  pymilvus_orm/prepare.py
  tests/test_schema.py
Labels: enhancement

#43 Update mergify
  .github/mergify.yml
Labels: enhancement

#44 Add partition impl in MockMilvus
  tests/mock_milvus.py
  tests/test_collection.py
  tests/test_partition.py
Labels: pr/automerge

#45 Fix some partition unittests
  pymilvus_orm/partition.py
  pymilvus_orm/prepare.py
  tests/test_index.py
  tests/test_partition.py
  tests/utils.py
Labels: pr/automerge

#46 Update GitHub Actions
  .github/workflows/integration.yml
  .github/workflows/pull_request.yml
  .gitignore
  Makefile
Labels: pr/automerge

#47 Add codecov badge in README.md
  README.md
Labels: pr/automerge

#50 Add an example
  Makefile
  examples/example.py
  pymilvus_orm/collection.py
  pymilvus_orm/connections.py
Labels: pr/automerge

#49 Delete auto_id param for collection schema
  pymilvus_orm/collection.py
Labels: pr/automerge

#51 Add copyright and modify params and documentation
  docs/draft/collection.md
  docs/draft/index.md
  docs/draft/partition.md
  docs/draft/schema.md
  examples/connections.py
  pymilvus_orm/__init__.py
  pymilvus_orm/collection.py
  pymilvus_orm/connections.py
  pymilvus_orm/constants.py
  pymilvus_orm/default_config.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
  pymilvus_orm/prepare.py
  pymilvus_orm/schema.py
  pymilvus_orm/search.py
  pymilvus_orm/types.py
  pymilvus_orm/utility.py
  tests/test_index.py
Labels: pr/automerge

#52 Update example
  examples/example.py
  examples/mock_milvus.py
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
  pymilvus_orm/schema.py
  pymilvus_orm/utility.py
  tests/mock_milvus.py
Labels: pr/automerge

#53 Add test for create index
  examples/collection.py
  pymilvus_orm/index.py
Labels: pr/automerge

#54 Add check in some interfaces
  pymilvus_orm/collection.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
  tests/test_index.py
  tests/test_partition.py
Labels: pr/automerge

#55 Add codecov config file
  codecov.yml
Labels: pr/automerge

#57 Update tests in test_partition
  .github/workflows/integration.yml
  Makefile
  pymilvus_orm/partition.py
  tests/mock_milvus.py
  tests/test_collection.py
  tests/test_connections.py
  tests/test_index.py
  tests/test_partition.py
  tests/test_schema.py
Labels: pr/automerge

#56 Add create index test for binary data
  examples/collection.py
  requirements.txt
Labels: pr/automerge

#58 Fix bug for inserting when collection schema has a primary field
  examples/collection.py
  pymilvus_orm/collection.py
  pymilvus_orm/prepare.py
Labels: pr/automerge

#59 Add TODO marks
  pymilvus_orm/collection.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
  pymilvus_orm/schema.py
  pymilvus_orm/search.py
  pymilvus_orm/utility.py
  tests/test_utility.py
Labels: pr/automerge

#60 Fix mistake return type
  pymilvus_orm/collection.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
Labels: pr/automerge

#62 Update todo items
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
  pymilvus_orm/utility.py
Labels: pr/automerge

#64 Fix todo lists
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
  tests/utils.py
Labels: pr/automerge

#65 Referencing other interfaces in interface comments
  docs/source/api/collection.rst
  docs/source/index.rst
  pymilvus_orm/collection.py
Labels: pr/automerge

#61 Add case when CollectionSchema specifies the primary field
  examples/collection.py
  pymilvus_orm/schema.py
Labels: pr/automerge

#66 Test trigger readocs
  examples/connections.py
Labels: pr/automerge

#68 Update unittest
  pymilvus_orm/partition.py
  tests/mock_milvus.py
  tests/test_collection.py
  tests/test_utility.py
Labels: pr/automerge

#69 Add interface documentation about collection
  docs/source/api/collection.rst
  pymilvus_orm/collection.py
Labels: pr/automerge

#67 Fix partition insert and add partition example
  examples/partition.py
Labels: bug, enhancement, pr/automerge

#63 Add util implements
  docs/draft/utility.md
  pymilvus_orm/utility.py
  tests/mock_milvus.py
  tests/test_utility.py
Labels: pr/automerge

#71 Add index related examples
  Makefile
  examples/example.py
  examples/example_index.py
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
  tests/mock_milvus.py
  tests/test_collection.py
  tests/test_index.py
  tests/utils.py
Labels: pr/automerge

#72 Add requirements for installing and add hello_milvus
  examples/hello_pymilvus_orm.py
  pymilvus_orm/__init__.py
  setup.py
Labels: pr/automerge

#73 Implement and add example to Collection.search
  pymilvus_orm/__init__.py
  pymilvus_orm/collection.py
  requirements.txt
Labels: enhancement, pr/automerge

#70 Add exceptions and errors class
  pymilvus_orm/exceptions.py
Labels: pr/automerge

#75 Add exceptions and errors in collection
  pymilvus_orm/collection.py
Labels: pr/automerge

#74 Add annotions in partition.py
  docs/source/api/partition.rst
  pymilvus_orm/exceptions.py
  pymilvus_orm/partition.py
Labels: pr/automerge

#76 Add interface connections
  docs/source/api/connections.rst
  docs/source/api/milvus_index.rst
  docs/source/api/schema.rst
  docs/source/api/search.rst
Labels: pr/automerge

#77 Improve the docstring of connections.Connections
  pymilvus_orm/connections.py
Labels: pr/automerge

#78 Format return
  pymilvus_orm/collection.py
Labels: pr/automerge

#80 update exception in index.py and add index.rst
  docs/draft/index.md
  docs/source/api/index.rst
  pymilvus_orm/exceptions.py
  pymilvus_orm/index.py
Labels: pr/automerge

#79 Move return type behind the return annotation in partition.py
  pymilvus_orm/partition.py
Labels: pr/automerge

#82 update return format in index.py
  pymilvus_orm/index.py
Labels: pr/automerge

#81 Improve hello_milvus file
  examples/hello_milvus.py
  examples/hello_pymilvus_orm.py
  pymilvus_orm/collection.py
Labels: pr/automerge

#83 Add wrapper to SearchResult-related class
  pymilvus_orm/collection.py
  pymilvus_orm/search.py
Labels: pr/automerge

#85 Add search for hello_milvus
  examples/hello_milvus.py
Labels: pr/automerge

#86 Add dim param example
  examples/example_index.py
Labels: pr/automerge

#84 Format collection exception raising
  pymilvus_orm/collection.py
Labels: pr/automerge

#87 add example for index.py
  pymilvus_orm/index.py
Labels: pr/automerge

#88 Add examples in partition.py
  pymilvus_orm/partition.py
Labels: pr/automerge

#89 Improve interface documentation
  docs/source/api/collection.rst
Labels: pr/automerge

#90 Add documentation to api reference of SearchResult, Hits, Hit
  docs/source/api/search.rst
  docs/source/conf.py
  pymilvus_orm/search.py
  requirements.txt
Labels: pr/automerge

#91 Add demo example to explain how to deal with search result
  docs/source/results.rst
Labels: pr/automerge

#92 Update index doc
  docs/source/res/Intro_to_Indexes.md
Labels: pr/automerge

#93 Improve documentation
  docs/source/about.rst
  docs/source/contribute.rst
  docs/source/faq.rst
  docs/source/install.rst
  docs/source/res/chang_log.md
Labels: pr/automerge

#95 Fix circular reference
  pymilvus_orm/__init__.py
  pymilvus_orm/collection.py
  pymilvus_orm/connections.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
  pymilvus_orm/schema.py
  pymilvus_orm/utility.py
  tests/conftest.py
  tests/test_connections.py
  tests/test_partition.py
  tests/utils.py
Labels: pr/automerge

#96 Update README
  CHANGELOG.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: pr/automerge

#97 Add utility doc
  pymilvus_orm/collection.py
  pymilvus_orm/index.py
  pymilvus_orm/utility.py
  tests/mock_milvus.py
Labels: pr/automerge

#98 Modify Index constructor
  pymilvus_orm/collection.py
  pymilvus_orm/index.py
Labels: pr/automerge

#99 Check and correct the documentation
  docs/source/api/search.rst
  pymilvus_orm/connections.py
Labels: pr/automerge

#100 Improve comment for collection
  pymilvus_orm/collection.py
Labels: pr/automerge

#101 Change readthedocs
  docs/source/api/api.rst
  docs/source/api/top_level_functions.rst
  docs/source/api/utility.rst
  pymilvus_orm/utility.py
Labels: pr/automerge

#102 Fix examples in index.py
  pymilvus_orm/index.py
Labels: pr/automerge

#103 Add a tutorial about how to use pymilvus-orm
  docs/source/tutorial.rst
Labels: pr/automerge

#104 Fix example/collection.py
  examples/collection.py
  pymilvus_orm/collection.py
  pymilvus_orm/index.py
Labels: pr/automerge

#105 Fix example/partition.py
  pymilvus_orm/partition.py
Labels: pr/automerge

#106 Update partition and index api doc
  docs/source/api/index.rst
  docs/source/api/partition.rst
Labels: documentation, pr/automerge

#107 Fix bug for auto_id
  pymilvus_orm/collection.py
Labels: pr/automerge

#109 Add descriptions of collection, partiton and index
  docs/source/api/collection.rst
  docs/source/api/index.rst
  docs/source/api/partition.rst
Labels: documentation, pr/automerge

#110 Add example for partition and index in collection
  pymilvus_orm/collection.py
Labels: pr/automerge

#111 Add comments to CollectionSchema and FieldSchema
  pymilvus_orm/schema.py
Labels: documentation, pr/automerge
