Repository milvus-io/pymilvus-orm, pull requests merged in 2021-06, with the labels that each got.

#142 Add get method in collection and partition
  docs/draft/collection.md
  docs/draft/partition.md
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
  requirements.txt
  tests/test_collection.py
  tests/test_partition.py
  tests/utils.py
Labels: approved, ci-passed, lgtm, size/M

#143 Support multi vector fields
  pymilvus_orm/collection.py
Labels: approved, size/XS

#145 Check schema when create collection by dataframe
  pymilvus_orm/collection.py
  pymilvus_orm/schema.py
Labels: pr/automerge, size/XS

#144 Check field type of schema
  pymilvus_orm/schema.py
Labels: pr/automerge, size/XS

#146 Update Mergify
  .github/mergify.yml
Labels: size/S

#148 Update Mergify
  .github/mergify.yml
Labels: approved, ci-passed, lgtm, size/XS

#147 Throw exception when the data in the same column is not the same type
  pymilvus_orm/collection.py
  pymilvus_orm/schema.py
Labels: approved, ci-passed, lgtm, size/M

#149 Update pymilvus version
  docs/source/install.rst
  pymilvus_orm/connections.py
  requirements.txt
  tests/conftest.py
  tests/mock_milvus.py
  tests/test_connections.py
Labels: approved, ci-passed, lgtm, size/M

#151 Upgrade pymilvus
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#150 Currently does not support numpy.ndarray.
  pymilvus_orm/prepare.py
Labels: approved, ci-passed, lgtm, size/XS

#152 Fix bug of insert
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
Labels: approved, ci-passed, lgtm, size/S

#153 Fix bug for insert
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
  pymilvus_orm/prepare.py
Labels: ci-passed, lgtm, size/S

#154 Create release_event.yml to dispatch orm release published event to Milvus doc repo
  .github/workflows/release_event.yml
Labels: approved, ci-passed, lgtm, size/S

#155 Throw exception of create instance while collection is None
  pylint.conf
  pymilvus_orm/collection.py
  pymilvus_orm/exceptions.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
  pymilvus_orm/utility.py
Labels: ci-passed, size/M

#156 Remove field_name for collection.indexes
  pymilvus_orm/collection.py
  pymilvus_orm/index.py
Labels: ci-passed, lgtm, size/XS

#159 Minor editorial updates
  pymilvus_orm/__init__.py
  pymilvus_orm/collection.py
  pymilvus_orm/connections.py
  pymilvus_orm/constants.py
  pymilvus_orm/default_config.py
  pymilvus_orm/exceptions.py
  pymilvus_orm/future.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
  pymilvus_orm/prepare.py
  pymilvus_orm/schema.py
  pymilvus_orm/search.py
  pymilvus_orm/types.py
  pymilvus_orm/utility.py
Labels: ci-passed, lgtm, size/L

#160 Change Connections to thread-safe singleton class
  pymilvus_orm/collection.py
  pymilvus_orm/connections.py
  tests/test_connections.py
Labels: ci-passed

#161 Add query api
  docs/draft/collection.md
  docs/draft/partition.md
  pylint.conf
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
  tests/test_collection.py
  tests/test_partition.py
Labels: approved, ci-passed

#162 Update documentation
  docs/source/api/connections.rst
Labels: approved, ci-passed, size/M

#163 Delete unused arguments
  pylint.conf
  pymilvus_orm/collection.py
  pymilvus_orm/connections.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
  tests/test_collection.py
  tests/test_index.py
Labels: approved, ci-passed, size/L

#164 Add class method for collection
  examples/collection.py
  examples/connections.py
  examples/example_index.py
  examples/hello_milvus.py
  examples/partition.py
  pymilvus_orm/collection.py
  tests/test_collection.py
Labels: approved, ci-passed, lgtm, size/M

#165 Rename expression to expr
  examples/example.py
  pymilvus_orm/collection.py
  requirements.txt
Labels: approved, ci-passed, lgtm, size/S

#167 Correct code in docs
  docs/source/tutorial.rst
Labels: approved, ci-passed, lgtm, size/S

#168 Update requirement pymilvus version
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#169 Checkout example
  examples/collection.py
  examples/connections.py
  examples/example_index.py
  examples/hello_milvus.py
  examples/partition.py
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
Labels: approved, ci-passed, lgtm, size/M

#170 Add deepcopy for FieldSchema
  pymilvus_orm/schema.py
Labels: approved, ci-passed, lgtm, size/S

#171 Check params for connections
  pymilvus_orm/connections.py
Labels: approved, ci-passed, lgtm, size/M

#172 fix binary vector dim
  pymilvus_orm/schema.py
Labels: approved, ci-passed, lgtm, size/S

#173 Update logic about auto_id
  examples/collection.py
  examples/example.py
  examples/example_index.py
  examples/hello_milvus.py
  examples/partition.py
  pymilvus_orm/collection.py
  pymilvus_orm/exceptions.py
  pymilvus_orm/partition.py
  pymilvus_orm/prepare.py
  pymilvus_orm/schema.py
  pymilvus_orm/search.py
  requirements.txt
  setup.py
  tests/mock_milvus.py
  tests/test_collection.py
  tests/test_schema.py
  tests/utils.py
Labels: approved, ci-passed, lgtm, size/L

#175 synchronize the latest pymilvus version
  requirements.txt
Labels: approved, ci-passed, lgtm, size/XS

#176 Remove unused print
  examples/example.py
Labels: approved, ci-passed, lgtm, size/XS

#174 Add to_dict & __eq__ for Index Class
  pymilvus_orm/index.py
Labels: approved, ci-passed, lgtm, size/S

#178 Check params for schema
  examples/example.py
  examples/example_index.py
  pymilvus_orm/partition.py
  pymilvus_orm/schema.py
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/M

#179 Add scsven into approvers
  OWNERS
Labels: approved, lgtm, size/XS

#182 Fix bug for auto_id in CollectionSchema
  pymilvus_orm/schema.py
Labels: approved, ci-passed, lgtm, size/XS

#181 Fix bug for constructing from dataframe
  examples/collection.py
  pymilvus_orm/collection.py
  pymilvus_orm/prepare.py
  tests/test_collection.py
Labels: approved, ci-passed, lgtm, size/S

#180 Update gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#183 Update the version of pymilvus
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#184 Update the version of pymilvus
  requirements.txt
  setup.py
Labels: ci-passed, size/XS

#186 Remove readthedocs as ci-passed requirements
  .github/mergify.yml
Labels: approved, ci-passed, lgtm, size/XS

#187 Add checks for alias
  pymilvus_orm/connections.py
Labels: approved, ci-passed, lgtm, size/S

#188 Update the version of pymilvus
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#185 Fix some bugs about collection
  pymilvus_orm/collection.py
  pymilvus_orm/prepare.py
  pymilvus_orm/search.py
Labels: approved, ci-passed, lgtm, size/M

#189 Simplify dependent packages
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/S

#191 Fix alias check bug
  pymilvus_orm/connections.py
  pymilvus_orm/utility.py
Labels: approved, ci-passed, lgtm, size/S

#190 Unified exception messages
  pymilvus_orm/collection.py
  pymilvus_orm/connections.py
  pymilvus_orm/exceptions.py
  pymilvus_orm/index.py
  pymilvus_orm/partition.py
  pymilvus_orm/prepare.py
  pymilvus_orm/schema.py
  pymilvus_orm/utility.py
  tests/test_connections.py
Labels: approved, ci-passed, lgtm, size/L

#193 Fix bug for two primary fields
  pymilvus_orm/schema.py
Labels: approved, ci-passed, lgtm, size/XS

#194 Update exception messages of connection interface
  pymilvus_orm/connections.py
Labels: approved, ci-passed, lgtm, size/XS

#195 Add expr type check
  pymilvus_orm/collection.py
  pymilvus_orm/exceptions.py
Labels: approved, ci-passed, lgtm, size/XS

#197 Rename SearchResultFuture and InsertFutue
  docs/draft/collection.md
  docs/source/api/future.rst
  pymilvus_orm/__init__.py
  pymilvus_orm/collection.py
  pymilvus_orm/future.py
  pymilvus_orm/partition.py
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/M

#196 Fix docs in collection object
  docs/source/api/collection.rst
  docs/source/conf.py
  pymilvus_orm/collection.py
Labels: ci-passed, size/XL

#201 Update doc
  docs/source/api/connections.rst
  docs/source/api/index.rst
  docs/source/api/milvus_index.rst
  docs/source/api/utility.rst
  docs/source/conf.py
  docs/source/faq.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/res/about_documentation.md
  docs/source/tutorial.rst
  pymilvus_orm/connections.py
  requirements.txt
Labels: approved, ci-passed, lgtm, size/L

#202 Update the version of pymilvus
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#204 Update publish GitHub Actions
  .github/workflows/publish_dev_package.yml
  .github/workflows/publish_release_package.yml
Labels: approved, ci-passed, lgtm, size/M

#203 Update dependent pymilvus version
  requirements.txt
  setup.py
Labels: approved, ci-passed, lgtm, size/XS

#206 Fix PyMilvus-ORM readme
  README.md
Labels: approved, ci-passed, lgtm, size/S

#207 Optimize import statement in comments
  docs/source/api/connections.rst
  docs/source/api/future.rst
  pymilvus_orm/collection.py
  pymilvus_orm/connections.py
Labels: approved, ci-passed, lgtm, size/L

#208 Fix utility.py example
  pymilvus_orm/utility.py
Labels: approved, ci-passed, lgtm, size/L

#209 Update test case of index in docs
  pymilvus_orm/index.py
Labels: approved, ci-passed, lgtm, size/S

#210 Fix comments in object partition
  pymilvus_orm/collection.py
  pymilvus_orm/partition.py
Labels: approved, ci-passed, lgtm, size/L

#211 Update test case in docs
  pymilvus_orm/schema.py
Labels: approved, ci-passed, lgtm, size/M

#212 Remove get method in draft
  docs/draft/collection.md
  docs/draft/partition.md
Labels: approved, ci-passed, lgtm, size/XS

#213 Get value of metadata fields from search result output
  CHANGELOG.md
  examples/hello_milvus.py
  pymilvus_orm/search.py
Labels: approved, ci-passed, lgtm, size/M

#214 Collection has no parameter of data
  examples/hello_milvus.py
Labels: approved, ci-passed, lgtm, size/XS

#215 Tidy example.py
  examples/hello_milvus.py
Labels: approved, ci-passed, lgtm, size/S

#218 Fix Intro_to_Indexes.md
  docs/source/res/Intro_to_Indexes.md
Labels: approved, ci-passed, lgtm, size/M

#217 Update documentation for pymilvus-orm
  docs/source/contribute.rst
  docs/source/install.rst
  docs/source/tutorial.rst
Labels: approved, ci-passed, lgtm, size/S

#219 Update changelog
  docs/source/res/chang_log.md
Labels: approved, ci-passed, lgtm, size/XS

#220 Fix bug about link in docs
  docs/source/tutorial.rst
Labels: approved, ci-passed, lgtm, size/XS
